services:
  mailserver_4LbF:
    image: mqxz/docker-mailserver-api
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    hostname: ${MAIL_HOSTNAME}
    ports:
      - ${HOST_IP}:${SMTP_PORT}:25
      - ${HOST_IP}:${SMTP_SSL_PORT}:465
      - ${HOST_IP}:${NSMTP_SSL_PORT}:587
      - ${HOST_IP}:${IMAP_PORT}:143
      - ${HOST_IP}:${IMAP_SSL_PORT}:993
      - ${HOST_IP}:${API_PORT}:8000
    volumes:
      - ${APP_PATH}/data/mail-data/:/var/mail/
      - ${APP_PATH}/data/mail-state/:/var/mail-state/
      - ${APP_PATH}/data/mail-logs/:/var/log/mail/
      - ${APP_PATH}/data/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      - ENABLE_RSPAMD=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - API_KEY=${API_KEY}
      - MIN_PASSWORD_LENGTH=${MIN_PASSWORD_LENGTH}
      - VERSION=${VERSION}
    networks:
      - mailserver

networks:
  mailserver:
    external: true
